[project]
name = "ComfyUI-WanVideoWrapper"
description = "ComfyUI diffusers wrapper nodes for WanVideo"
version = "1.1.7"
license = {file = "LICENSE"}
dependencies = ["accelerate >= 1.2.1", "diffusers >= 0.32.0", "ftfy"]

[project.urls]
Repository = "https://github.com/kijai/ComfyUI-WanVideoWrapper"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "kijai"
DisplayName = "ComfyUI-WanVideoWrapper"
Icon = ""


[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = [ 
    "ComfyUI_WanVideo_nodes", 
    "ComfyUI_WanVideo_nodes.configs",
    "ComfyUI_WanVideo_nodes.diffsynth.vram_management",
    "ComfyUI_WanVideo_nodes.enhance_a_video",
    "ComfyUI_WanVideo_nodes.fantasytalking",
    "ComfyUI_WanVideo_nodes.fun_camera",
    "ComfyUI_WanVideo_nodes.recammaster",
    "ComfyUI_WanVideo_nodes.skyreels",
    "ComfyUI_WanVideo_nodes.taehv",
    "ComfyUI_WanVideo_nodes.unianimate",
    "ComfyUI_WanVideo_nodes.unianimate.dwpose",
    "ComfyUI_WanVideo_nodes.wanvideo",
    "ComfyUI_WanVideo_nodes.wanvideo.configs",
    "ComfyUI_WanVideo_nodes.wanvideo.modules",
    "ComfyUI_WanVideo_nodes.wanvideo.utils",
]

[tool.setuptools.package-dir]
"ComfyUI_WanVideo_nodes" = "."
"ComfyUI_WanVideo_nodes.configs" = "configs"
"ComfyUI_WanVideo_nodes.enhance_a_video" = "enhance_a_video"
"ComfyUI_WanVideo_nodes.diffsynth.vram_management" = "diffsynth/vram_management"
"ComfyUI_WanVideo_nodes.fantasytalking" = "fantasytalking"
"ComfyUI_WanVideo_nodes.fun_camera" = "fun_camera"
"ComfyUI_WanVideo_nodes.recammaster" = "recammaster"
"ComfyUI_WanVideo_nodes.skyreels" = "skyreels"
"ComfyUI_WanVideo_nodes.taehv" = "taehv"
"ComfyUI_WanVideo_nodes.unianimate" = "unianimate"
"ComfyUI_WanVideo_nodes.unianimate.dwpose" = "unianimate.dwpose"
"ComfyUI_WanVideo_nodes.wanvideo" = "wanvideo"
"ComfyUI_WanVideo_nodes.wanvideo.configs" = "wanvideo/configs"
"ComfyUI_WanVideo_nodes.wanvideo.modules" = "wanvideo/modules"
"ComfyUI_WanVideo_nodes.wanvideo.utils" =  "wanvideo/utils"

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[tool.setuptools.package-data]
"*" = ["**/*.js", "**/*.json", "**/*.model", "*.pt"]

[project.entry-points."comfyui.custom_nodes"]
ComfyUI_WanVideo_nodes = "ComfyUI_WanVideo_nodes"